//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoGamesEncyclopedia.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VideoGamesEncyclopediaDbEntities : DbContext
    {
        public VideoGamesEncyclopediaDbEntities()
            : base("name=VideoGamesEncyclopediaDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<ignoredproduct> ignoredproducts { get; set; }
        public virtual DbSet<productcategory> productcategories { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<productscreenshot> productscreenshots { get; set; }
        public virtual DbSet<rating> ratings { get; set; }
        public virtual DbSet<recommendation> recommendations { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<wishedproduct> wishedproducts { get; set; }
    }
}
