//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoGamesEncyclopedia.Models
{
    using System;

    public partial class recommendation
    {
        public recommendation(int newRecommendationId, string v1, int productId, int rate, bool v2, DateTime now)
        {
            Id = newRecommendationId;
            UserId = v1;
            ProductId = productId;
            RecommendationRating = rate;
            WasPresented = v2;
            GenerationDate = now;
        }

        public recommendation()
        {

        }

        public int Id { get; set; }
        public string UserId { get; set; }
        public int ProductId { get; set; }
        public float RecommendationRating { get; set; }
        public bool WasPresented { get; set; }
        public System.DateTime GenerationDate { get; set; }
    
        public virtual aspnetuser aspnetuser { get; set; }
        public virtual product product { get; set; }
    }
}
