//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoGamesEncyclopedia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class recommendation
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int ProductId { get; set; }
        public float RecommendationRating { get; set; }
        public bool WasPresented { get; set; }
        public System.DateTime GenerationDate { get; set; }
    
        public virtual product product { get; set; }
        public virtual user user { get; set; }
    }
}
