//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoGamesEncyclopedia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wishedproduct
    {
        public wishedproduct(string userId, int productId)
        {
            UserId = userId;
            ProductId = productId;
        }

        public wishedproduct()
        {

        }

        public int Id { get; set; }
        public string UserId { get; set; }
        public int ProductId { get; set; }
    
        public virtual aspnetuser aspnetuser { get; set; }
        public virtual product product { get; set; }
    }
}
